# Generated by Django 2.0.1 on 2018-02-11 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=30)),
                ('post_text', models.CharField(max_length=12)),
                ('publication_date', models.DateTimeField(verbose_name='date of publication')),
            ],
        ),
    ]
