# Generated by Django 2.0.1 on 2018-02-17 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_comment_approval'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='approval',
            new_name='approved',
        ),
    ]
